name: release

on:
  workflow_dispatch:
    branches:
      - 'v*.*'

permissions:
  contents: write

jobs:
  release:
    uses: calq-framework/stable-flow/.github/workflows/stableflow.yaml@main
    with:
      command: release
    secrets:
      MAIN_NUGET_PAT: ${{ secrets.MAIN_NUGET_PAT }}
      CALQ_FRAMEWORK_NUGET_PAT: ${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }}
