name: stableflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

concurrency: stableflow

permissions:
  contents: write

jobs:
  stableflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          - 7.0.x
          - 8.0.x
    - name: import secrets as env vars
      run: |
        SECRETS_JSON=$(echo '${{ toJson(secrets) }}')
        for key in $(echo "${SECRETS_JSON}" | jq -r 'keys[]'); do
          value=$(echo "${SECRETS_JSON}" | jq -r --arg key "${key}" '.[$key]')
          echo "${key}=${value}" >> $GITHUB_ENV
          echo "${key}"
        done
    - name: get called workflow ref
      id: workflows-ref
      run: |
        workflow_ref=${{ github.workflow_ref }}
        repository="${{ github.repository }}/"
        ref="@${{ github.ref }}"
        workflow_path=${workflow_ref#"$repository"}
        workflow_path=${workflow_path%"$ref"}
        called_workflow_ref=$(cat "$workflow_path" | grep 'uses: calq-framework/stableflow/.github/workflows/stableflow.yaml' | cut -d"@" -f2 | tr -d '[:space:]')
        echo "CALLED_WORKFLOW_REF=$called_workflow_ref" >> $GITHUB_ENV
        echo "CALLED_WORKFLOW_REF: \"$called_workflow_ref\""
    - name: setup nuget config
      run: |
        echo "~/.config/NuGet/NuGet.Config"
        cat ~/.config/NuGet/NuGet.Config || true
        echo "~/.nuget/NuGet/NuGet.Config"
        cat ~/.nuget/NuGet/NuGet.Config || true
        temp_dir=$(mktemp -d)
        if git clone --depth 1 https://github.com/${{ github.repository_owner }}/.nuget "$temp_dir"; then
          echo "pulled"
          mkdir ~/.nuget
          cp -r $temp_dir/.nuget ~/
          if [ -f ~/.nuget/NuGet/NuGet.Config ]; then
            temp_file=$(mktemp)
            envsubst < ~/.nuget/NuGet/NuGet.Config > "$temp_file" && mv "$temp_file" ~/.nuget/NuGet/NuGet.Config
          fi
        fi
        rm -rf "$temp_dir"
        echo "~/.config/NuGet/NuGet.Config"
        cat ~/.config/NuGet/NuGet.Config || true
        echo "~/.nuget/NuGet/NuGet.Config"
        cat ~/.nuget/NuGet/NuGet.Config || true
    - name: install stableflow
      shell: bash
      run: |
        if [[ "${{ github.repository }}" != "calq-framework/stableflow" ]]; then
          echo "CALLED_WORKFLOW_REF: $CALLED_WORKFLOW_REF"
          version=""
          if [[ "$CALLED_WORKFLOW_REF" == "latest" ]]; then
            version='*'
          else
            echo "CALLED_WORKFLOW_REF: \"$CALLED_WORKFLOW_REF\""
            version=$(echo "$CALLED_WORKFLOW_REF" \
              | grep -o 'v[0-9]*\.[0-9]*\.[0-9]*' \
              | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
          fi
          echo "installing CalqFramework.Stableflow $version"
          dotnet tool update --global CalqFramework.Stableflow --version "$version"
        fi
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: self-install stableflow
      shell: bash
      run: |
        if [[ "${{ github.repository }}" == "calq-framework/stableflow" ]]; then
          dotnet tool uninstall --global CalqFramework.Stableflow || true
          dotnet pack -c Release --output .
          nupkg=$(find . -maxdepth 1 -type f -name "*.nupkg")
          version=$(echo "$nupkg" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\)\.nupkg/\1/p')
          dotnet tool install --global --add-source . --version "$version" CalqFramework.Stableflow # doesn't use local source unless version is specified
        fi
    - name: stableflow
      shell: bash
      run: stableflow ${{ inputs.command }}
