name: stableflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      MAIN_NUGET_PAT:
        required: true
      CALQ_FRAMEWORK_NUGET_PAT:
        required: true

concurrency: stableflow

permissions:
  contents: write

jobs:
  stableflow:
    runs-on: ubuntu-latest
    steps:
    - name: setup nuget config
      continue-on-error: true
      run: |
        dotnet nuget add source --username ${{ github.triggering_actor }} --password ${{ secrets.MAIN_NUGET_PAT }} --store-password-in-clear-text --name main "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
        dotnet nuget add source --username ${{ github.triggering_actor }} --password ${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }} --store-password-in-clear-text --name calq-framework "https://nuget.pkg.github.com/calq-framework/index.json"
    - name: download synver metadata
      run: |
        PACKAGE_ID="CalqFramework.Synver"
        PACKAGE_OWNER="calq-framework"
        TOOL_METADATA_DIR=".dotnet/tools/.metadata/$PACKAGE_ID"
        mkdir -p $TOOL_METADATA_DIR
        curl --fail --output "$TOOL_METADATA_DIR/index.json" "https://${{ github.triggering_actor }}:${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }}@nuget.pkg.github.com/$PACKAGE_OWNER/$PACKAGE_ID/index.json"
    - name: download stableflow metadata
      run: |
        PACKAGE_ID="CalqFramework.Stableflow"
        PACKAGE_OWNER="calq-framework"
        TOOL_METADATA_DIR=".dotnet/tools/.metadata/$PACKAGE_ID"
        mkdir -p $TOOL_METADATA_DIR
        curl --fail --output "$TOOL_METADATA_DIR/index.json" "https://${{ github.triggering_actor }}:${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }}@nuget.pkg.github.com/$PACKAGE_OWNER/$PACKAGE_ID/index.json"
    - uses: actions/cache@v3
      with:
        path: ~/.dotnet/tools
        key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('.dotnet/tools/.metadata/*/index.json') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-tools-
    - name: install synver
      shell: bash
      run: |
        if [[ "${{ github.repository }}" != "calq-framework/synver" ]]; then
          dotnet tool update --global CalqFramework.Stableflow # TODO --version ${{ github.workflow_ref }}
        fi
    - name: install stableflow
      shell: bash
      run: |
        if [[ "${{ github.repository }}" != "calq-framework/stableflow" ]]; then
          dotnet tool update --global CalqFramework.Stableflow # TODO --version ${{ github.workflow_ref }}
        fi
    - name: clean workdir
      run: rm -rf *
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: self-install synver
      shell: bash
      run: |
        if [[ "${{ github.repository }}" == "calq-framework/synver" ]]; then
          dotnet tool uninstall --global CalqFramework.Synver || true
          dotnet pack -c Release --output .
          nupkg=$(find . -maxdepth 1 -type f -name "*.nupkg")
          version=$(echo "$nupkg" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\)\.nupkg/\1/p')
          dotnet tool install --global --add-source . --version "$version" CalqFramework.Synver # doesn't use local source unless version is specified
        fi
    - name: self-install stableflow
      shell: bash
      run: |
        if [[ "${{ github.repository }}" == "calq-framework/stableflow" ]]; then
          dotnet tool uninstall --global CalqFramework.Stableflow || true
          dotnet pack -c Release --output .
          nupkg=$(find . -maxdepth 1 -type f -name "*.nupkg")
          version=$(echo "$nupkg" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\)\.nupkg/\1/p')
          dotnet tool install --global --add-source . --version "$version" CalqFramework.Stableflow # doesn't use local source unless version is specified
        fi
    - name: stableflow
      shell: bash
      run: stableflow ${{ inputs.command }}
