name: merge-release

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-release:
    uses: calq-framework/stable-flow/.github/workflows/stableflow.yaml@main
    with:
      command: merge -r
    secrets:
      MAIN_NUGET_PAT: ${{ secrets.MAIN_NUGET_PAT }}
      CALQ_FRAMEWORK_NUGET_PAT: ${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }}
